package aaa.assignment3;

import java.util.*;

import aaa.*;

public class StateMulti implements State
{
	private final Agent prey;
	private final List<Agent> predators;
	
	private HashMap<Agent, Integer> x;
	private HashMap<Agent, Integer> y;
	
	private HashMap<Agent, Integer> xDist;
	private HashMap<Agent, Integer> yDist;
	
	public StateMulti(Agent prey, List<Agent> predators)
	{
		this.prey      = prey;
		this.predators = predators;
		
		x = new HashMap<Agent, Integer>();
		y = new HashMap<Agent, Integer>();
		
		xDist = new HashMap<Agent, Integer>();
		yDist = new HashMap<Agent, Integer>();
		
		x.put(prey, 5);
		y.put(prey, 5);
		
		switch (predators.size())
		{
			case 4:
				x.put(predators.get(3), 0);
				y.put(predators.get(3), 10);
			case 3:
				x.put(predators.get(2), 10);
				y.put(predators.get(2), 0);
			case 2:
				x.put(predators.get(1), 10);
				y.put(predators.get(1), 10);
			case 1:
				x.put(predators.get(0), 0);
				y.put(predators.get(0), 0);
		}
		
		calculateDistances();
	}

	@Override
	public Iterator<State> stateIterator()
	{
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isFinal()
	{
		return collisionPrey() || collisionPredators();
	}

	@Override
	public int getX(Agent agent)
	{
		return x.get(agent);
	}

	@Override
	public int getY(Agent agent)
	{
		return y.get(agent);
	}

	@Override
	public void move(Agent agent)
	{
		float sum    = 0;
		float random = (float) Math.random();
		
		for (int action: AGENT_ACTIONS)
		{
			sum += agent.pi(this, action);
			
			if (sum >= random)
			{
				move(agent, action);
				
				break;
			}
		}
	}
	
	@Override
	public void move(Agent agent, int action)
	{
		float random = (float) Math.random();
		
		if (agent.getType() != Agent.TYPE_PREY || random > 0.2f) // Prey tripping behaviour.
		{
			if (action % 2 == 0)
			{
				x.put(agent, StateSimple.fixCoord(x.get(agent) + action / 2));
			}
			else
			{
				y.put(agent, StateSimple.fixCoord(y.get(agent) + action));
			}
		}
		
		calculateDistances();
	}
	
	@Override
	@SuppressWarnings("unchecked")
	public Object clone()
	{
		StateMulti clone = new StateMulti(prey, predators);
		
		clone.x = (HashMap<Agent, Integer>) x.clone();
		clone.y = (HashMap<Agent, Integer>) y.clone();
		
		clone.xDist = (HashMap<Agent, Integer>) xDist.clone();
		clone.yDist = (HashMap<Agent, Integer>) yDist.clone();
		
		return clone;
	}
	
	public int getReward(Agent agent)
	{
		if (collisionPredators())
		{
			if (agent.getType() == Agent.TYPE_PREDATOR)
			{
				return -10;
			}
			else // Agent.TYPE_PREY
			{
				return +10;
			}
		}
		else if (collisionPrey())
		{
			if (agent.getType() == Agent.TYPE_PREDATOR)
			{
				return +10;
			}
			else // Agent.TYPE_PREY
			{
				return -10;
			}
		}
		else
		{
			return 0;
		}
	}
	
	private boolean collisionPredators()
	{
		for (int i = 0; i < predators.size(); i++)
		{
			for (int j = i + 1; j < predators.size(); j++)
			{
				Agent predatorA = predators.get(i);
				Agent predatorB = predators.get(j);
				
				if (getX(predatorA) == getX(predatorB) && getY(predatorA) == getY(predatorB))
				{
					return true;
				}
			}
		}
		
		return false;
	}
	
	private boolean collisionPrey()
	{
		for (Agent predator: predators)
		{
			if (getX(predator) == getX(prey) && getY(predator) == getY(prey))
			{
				return true;
			}
		}
		
		return false;
	}
	
	private void calculateDistances()
	{
		for (Agent predator: predators)
		{
			int innerX = x.get(prey) - x.get(predator);
			int outterX;
			
			if (innerX < 0)
			{
				outterX = innerX + ENVIRONMENT_SIZE;
			}
			else
			{
				outterX = innerX - ENVIRONMENT_SIZE;
			}
			
			if (Math.abs(innerX) < Math.abs(outterX))
			{
				xDist.put(predator, innerX);
			}
			else
			{
				xDist.put(predator, outterX);
			}
			
			int innerY = y.get(prey) - y.get(predator);
			int outterY;
			
			if (innerY < 0)
			{
				outterY = innerY + ENVIRONMENT_SIZE;
			}
			else
			{
				outterY = innerY - ENVIRONMENT_SIZE;
			}
			
			if (Math.abs(innerY) < Math.abs(outterY))
			{
				yDist.put(predator, innerY);
			}
			else
			{
				yDist.put(predator, outterY);
			}
		}
	}

	@Override
	public int hashCode()
	{
		final int[] primes = new int[] {19, 23, 29, 31};
		final int   prime  = primes[predators.size() - 1];
		
		int result = 1;
		
		for (Agent predator: predators)
		{
			result = prime * result + xDist.get(predator);
			result = prime * result + yDist.get(predator);
		}
		
		return result;
	}
	
	// Automatically-generated by Eclipse:
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StateMulti other = (StateMulti) obj;
		if (xDist == null) {
			if (other.xDist != null)
				return false;
		} else if (!xDist.equals(other.xDist))
			return false;
		if (yDist == null) {
			if (other.yDist != null)
				return false;
		} else if (!yDist.equals(other.yDist))
			return false;
		return true;
	}
}
