package assignment1;

import java.util.Iterator;

public class StateReduced extends StateSimple
{
	int distanceX, distanceY;
	
	public StateReduced(int predatorX, int predatorY, int preyX, int preyY)
	{
		super(predatorX, predatorY, preyX, preyY);
		
		int distX1 = preyX - predatorX;
		int distX2 = distX1 - ENVIRONMENT_SIZE;
		
		if (Math.abs(distX1) < Math.abs(distX2))
		{
			distanceX = distX1;
		}
		else
		{
			distanceX = distX2;
		}
		
		int distY1 = preyY - predatorY;
		int distY2 = distY1 - ENVIRONMENT_SIZE;
		
		if (Math.abs(distY1) < Math.abs(distY2))
		{
			distanceY = distY1;
		}
		else
		{
			distanceY = distY2;
		}
	}
	
	@Override
	public Iterator<State> stateIterator()
	{
		class IteratorStates implements Iterator<State>
		{
			private boolean hasNext;
			
			private int x, y;
			
			public IteratorStates()
			{
				hasNext = true;
				
				x = 0;
				y = 0;
			}
			
			@Override
			public boolean hasNext()
			{
				return hasNext;
			}

			@Override
			public State next() // TODO: Wrong!
			{
				State nextState = new StateReduced(x, y, 5, 5);
				
				x++;
				
				if (x >= 6)
				{
					x = 0;
					
					y++;
					
					if (y >= 6)
					{
						hasNext = false;
					}
				}
				
				return nextState;
			}

			@Override
			public void remove()
			{
				// TODO Auto-generated method stub
			}
		}
		
		return new IteratorStates();
	}
	
	@Override
	public Object clone()
	{
		return new StateReduced(x[Agent.TYPE_PREDATOR], y[Agent.TYPE_PREDATOR], x[Agent.TYPE_PREY], y[Agent.TYPE_PREY]);
	}
	
	// Automatically-generated by Eclipse:

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + distanceX;
		result = prime * result + distanceY;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		StateReduced other = (StateReduced) obj;
		if (distanceX != other.distanceX)
			return false;
		if (distanceY != other.distanceY)
			return false;
		return true;
	}
}
